### ISSUE TITLE
Breakpoint on exception stops on LoggerFactory

### ISSUE THREAD

**Issue by komocode** [danikula/Google-Play-Expansion-File#2]
In DownloaderClientMarshaller.java, a breakpoint stops at:
`private static final Logger LOG = LoggerFactory.getLogger("DownloaderClientMarshaller");`

And causes my app to crash. 

I've tried adding

```
    compile 'org.slf4j:slf4j-api:1.7.7'
    compile files('libs/slf4j-simple-1.7.21.jar')
```

to my build.gradle, but it doesn't alleviate the problem.

I'm using Android Studio 2.1.2, JDK 1.7.0, and using:

```
    compile 'com.danikula.expansion:expansion:1.3.3@aar'
    compile 'com.danikula.expansion:license:1.7.0@aar'
    compile 'com.danikula.expansion:zip:1.2.1@aar'
```

**Comment by danikula** [comment]
Try to use 

```
compile 'org.bitbucket.yahor_makouski:slf4j-composite:1.2'
compile 'org.slf4j:slf4j-api:1.7.18'
```
