### ISSUE TITLE
XAPK File Validation Failed.

### ISSUE THREAD

**Issue by HareshChhelana** [danikula/Google-Play-Expansion-File#3]
I have created .obb file using zip command in mac with no compression and check expansion with manually place .obb file on device desired location it work perfectly but when i upload signed APK in alpha testing along with .bbb file expansion and try to check real expansion downloading it will show "XAPK File Validation Failed." Please help to resolve this problem.

**Comment by danikula** [comment]
All you need you can find [here](https://developer.android.com/google/play/expansion-files.html). This project is out of scope your problem.
